### ISSUE TITLE
Possible to add Pollen and Air Quality 

### ISSUE THREAD

**Issue by holdestmade** [r-renato/ha-climacell-weather#1]
Would it be possible to add Pollen and Air Quality to the HA sensor ?

**Comment by r-renato** [comment]
yes, is  possible. The released 1.1.0 version add Air Quality, Pollen and Fire risk data.
enjoy.

**Comment by holdestmade** [comment]
Brilliant, works great, many thanks

**Comment by r-renato** [comment]
sorry, no. the climate cell doesn't provide a forecast for this data.

**Comment by holdestmade** [comment]
OK thanks

**Comment by holdestmade** [comment]
Hi, just been playing with the API for pollen and I think this gives 108 hours of pollen_tree forecast ?

https://api.climacell.co/v3/weather/forecast/hourly?lat=XXXXXX&lon=XXXXXX&fields=pollen_tree&apikey=XXXXXXXXXXXXXXXXXXXXXXXXXXXX
