### ISSUE TITLE
[Bug] Fire Index and Air Quality Index do not get recognized as numerical sensors in HA

### ISSUE THREAD

**Issue by ajayjohn** [r-renato/ha-climacell-weather#14]
As you can see in the screenshots, though the value for these sensors is a float value, HA seems to treat them like text values.
Consequently, HA doesn't show any kind of history graph for these values either. I read somewhere that this happens if you define a sensor without a unit and a device class.

<img width="364" alt="Screen Shot 2020-07-08 at 10 34 44 PM" src="https://user-images.githubusercontent.com/1575879/86994274-9abd9a80-c16b-11ea-83f2-b418f440fd96.png">
<img width="364" alt="Screen Shot 2020-07-08 at 10 34 29 PM" src="https://user-images.githubusercontent.com/1575879/86994277-9beec780-c16b-11ea-8fc8-e3d44fa8065d.png">

**Comment by r-renato** [comment]
I've added the unit of measurement for the fire index and epa, that answers your question.

Thanks,
Renato

**Comment by ajayjohn** [comment]
Works perfectly now. Thanks!
