### ISSUE TITLE
[Feature Request] High/low temp for the day

### ISSUE THREAD

**Issue by MYeager1967** [r-renato/ha-climacell-weather#19]
Since I'm using this as part of an irrigation management system, two of the sensors required is high and low temp for the day. I had a custom AppDaemon routine that was doing what your integration does and I had created the extra sensors that simply reset to the current temperature at midnight. Can you incorporate this feature? It will save anyone that needs it from having to do it themselves.

if you'd be so kind as to consider calling them sensor.cc_lowtoday and sensor.cc_hightoday, it would save me having to redo a lot of my work.

**Comment by r-renato** [comment]
Hi,
the daily temperature forecast expose two sensors (min and max) for each observation days. Day 0 is today. 
Are these two sensors useful for you irrigation management system?

Renato

**Comment by MYeager1967** [comment]
I didn't realize they were there but I'll look into it. As it is, I have a set of sensors that update throughout the day as the temp changes.

**Comment by MYeager1967** [comment]
I looked into this and I don't see those because I'm not grabbing that particular data set. It's all good and I'll continue doing what I'm doing. Thanks for the work on creating this component...
