### ISSUE TITLE
Interested in collaborating?

### ISSUE THREAD

**Issue by raman325** [r-renato/ha-climacell-weather#23]
Hey there,

Recently came across this integration in a Reddit thread. Not sure if you published this before I started working on my own integration or not (I could have sworn I checked), but I have a PR open to add a `climacell` integration to `home-assistant/core` (home-assistant/core#36547). Would you be interested in collaborating on an "official" integration and trying to merge these together? From the looks of it, we went with different design approaches - I tried to conform to HA's standards for their core integrations, but I am definitely open to changing some of the design decisions if it makes sense. Anyway, let me know, it'd be great to have two heads instead of one on it. Cheers!

BTW - if you'd prefer to keep these projects independent, I totally understand, you have a lot more freedom with integrations outside of the core list.

**Comment by r-renato** [comment]
hi,
how can I see the source code? What is the repository link?

**Comment by raman325** [comment]
You can see the code here: https://github.com/raman325/home-assistant/tree/climacell/homeassistant/components/climacell
