### ISSUE TITLE
Question on Forecast_Observations

### ISSUE THREAD

**Issue by gdreelin** [r-renato/ha-climacell-weather#3]
When using the "forecast_observations" how would you show that in the config?

forecast_observations: 7
or
forecast_observations:
7 

or something else?

**Comment by r-renato** [comment]
Hi,
the right assignment is `forecast_observations: 7`, but for a bug this one didn't work.
I have fixed the bug and released a new version. 

Thanks for your report.
Renato

**Comment by gdreelin** [comment]
Thanks
