### ISSUE TITLE
API 3 stopping soon and V4 didnt seem to work 

### ISSUE THREAD

**Issue by doojit** [r-renato/ha-climacell-weather#35]
Hi many thanks for a great plugin, I could not get the V4 API to work 3 works fine but emailed climacell and they advise that V3 will be stopping soon. 

   Paul,      You may register to V3 here: https://developer.climacell.co/register 
   Having said that, V3 will be discontinued in the next few week and we   strongly recommend you sign up to our V4.

      Jacob   

Best Regard,   ClimaCell Customer Success Team
--

**Comment by r-renato** [comment]
Thank you, I know, but I am very busy at the moment. I hope to work on the update soon.

**Comment by doojit** [comment]
Hi no problems many thanks great app, it was more just popping the update from Climacell many thanks great work have a good weekend.

**Comment by Giuliointhetube** [comment]
I think can be helpful to have a full list of fields available in Climacell's V4 API.
@r-renato all those are already working with your integration (tested).
All the listed fields listed are part of the Free Climacell API plan.

        fields:
          - temperature
          - temperatureApparent
          - dewPoint
          - humidity
          - windSpeed
          - windDirection
          - windGust
          - pressureSurfaceLevel
          - pressureSeaLevel
          - precipitationIntensity
          - precipitationProbability
          - precipitationType
          - visibility
          - cloudCover
          - cloudBase
          - cloudCeiling
          - moonPhase
          - weatherCode
          - sunriseTime
          - sunsetTime
          - treeIndex
          - grassIndex
          - weedIndex
          - particulateMatter25
          - particulateMatter10
          - pollutantO3
          - pollutantNO2
          - pollutantCO
          - pollutantSO2
          - mepIndex
          - mepPrimaryPollutant
          - mepHealthConcern
          - epaIndex
          - epaPrimaryPollutant
          - epaHealthConcern
          - fireIndex
          - solarGHI
