### ISSUE TITLE
ClimaCell v3 deprecation

### ISSUE THREAD

**Issue by climagene** [r-renato/ha-climacell-weather#36]
ClimaCell has released a new API (v4) and will be deprecating the old API (v3) over the next few months. To avoid any major issues, please point users to the new API signup page (https://www.climacell.co/pricing) and the new documentation (https://docs.climacell.co/) and adjust the code to leverage the new v4 endpoints.

**Comment by mfabiani53** [comment]
Me too saw this deprecation and, before upgrading the custom component, i'd like to have a complete list of the breaking changes in the sensors configuration. In the read.me file i only see an example but not a complete list of the changes needed to the configuration.

**Comment by r-renato** [comment]
Thanks @climagene, the new released component use the climacell api version 4.
