### ISSUE TITLE
Wrong metric windspeed

### ISSUE THREAD

**Issue by GKHerping** [r-renato/ha-climacell-weather#65]
Using: [https://github.com/L1p0-M/ha-climacell-weather](url)

<img width="472" alt="image" src="https://user-images.githubusercontent.com/22987583/152117370-91fc1603-bb3b-4c21-b259-3bf36af41950.png">

As you can see the windspeed is shown in km/h but Climacell [https://docs.tomorrow.io/reference/data-layers-core](url) uses m/s for metric system

**Comment by L1p0-M** [comment]
I looked at it, but i think the issue is with the card ,what you using to display it,because the sensor reports m/s
![speedfromsensor](https://user-images.githubusercontent.com/36809632/153706489-66f30ff4-09a3-45a7-8f02-ea82f652196b.PNG)
!
As you can see here.

**Comment by GKHerping** [comment]
Apologies, I realise I have uploaded the issue to the wrong place. R-renato is also the creator for the card. I'll upload there
