### ISSUE TITLE
Detected integration that accesses the `is_metric` property of the unit system.

### ISSUE THREAD

**Issue by tarheelz** [r-renato/ha-climacell-weather#69]
`Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for climacell_custom using this method at custom_components/climacell_custom/sensor.py, line 112: elif hass.config.units.is_metric:`

Admittedly, I am running the custom fork from @L1p0-M https://github.com/L1p0-M/ha-climacell-weather but presumably this is true here as well.

**Comment by L1p0-M** [comment]
Fixed it! btw you can report issues to my fork as well!
