### ISSUE TITLE
Climacell Nowcast

### ISSUE THREAD

**Issue by alvaro-duarte** [r-renato/ha-climacell-weather#7]
Hi,

This is not quite an issue, but more a suggestion for improvement.

I am using your HACS integration for Climacell and it looks pretty well. Thanks for the nice job.

Are you considering getting the data for Nowcast (https://developer.climacell.co/v3/docs/forecast#section-nowcast)? With that, available on the free API as well, there is the possibility to have a shorter term forecast and keep an eye on when rain (as an example) is about to start falling.

Appreciate the work.

Cheers,

**Comment by ilfandango** [comment]
+1 for this enhancement! And thank you for your integration and the relative card.

**Comment by r-renato** [comment]
Hi,
this feature is present in the new released component version.

Thanks,
Renato

**Comment by alvaro-duarte** [comment]
Hi,

Great. Thanks for the work on this.

Are you also updating the lovelace card for Climacel to include the new sensors? Nice work.

Cheers,
