### ISSUE TITLE
[Feature Request] Support for hourly forecasts

### ISSUE THREAD

**Issue by ajayjohn** [r-renato/ha-climacell-weather#8]
I can't thank you enough for creating this awesome integration, especially after Dark Sky can no longer be depended on. While everything you have built till now works perfectly, I was hoping to suggest a new feature.

Could you please add support for hourly forecasts as well? This seems to be available in the free plan and could be great for aspects like predicting overnight weather or knowing whether it will rain between a certain time range.

https://developer.climacell.co/v3/reference#get-hourly

**Comment by r-renato** [comment]
Hi,
this feature is present in the new released component version.

Thanks,
Renato

**Comment by ajayjohn** [comment]
Thanks a lot the prompt response!
BTW, do you have any plans to merge all sensors of each class (hourly, daily) as a single sensor with multiple attributes?

**Comment by r-renato** [comment]
Hi, not at the moment, but you want to give me an example?

**Comment by ajayjohn** [comment]
I meant using a single entity for hourly or daily forecast and providing all the values related to it as an array of attributes available on it. I am not sure if this something the custom component takes care of or if it is handled by HA itself. But, this is how all the weather type entities work.

Attached here is an example of how the NOAA component work. If you notice here, there is only one entity for the daily forecast. However, the entity holds the attributes needed for each and every forecast timestep. I feel like the Climacell component, as it adds more and more attributes, can make use of such a structure to avoid too many new entities from being created. (I can open a new issue for this if you'd like.
![Screen Shot 2020-07-02 at 4 03 24 PM](https://user-images.githubusercontent.com/1575879/86409319-45bae980-bc7e-11ea-8f7b-d14fbcff3255.png)
![Screen Shot 2020-07-02 at 4 04 05 PM](https://user-images.githubusercontent.com/1575879/86409334-49e70700-bc7e-11ea-8f53-01d8dbe6877e.png)

**Comment by ajayjohn** [comment]
I went ahead an opened a new issue for this, so that the details don't get lost.
Thank you so much for all the effort you are putting into this component!
